### ISSUE TITLE
More comments needed in code for comprehension

### ISSUE THREAD

**Issue by billyedwards3017** [billyedwards3017/CMP1903MOOPAssignment-1#9]
we need to include more comments in the code so that anyone looking at it can easily understand what is working.

**Comment by smexycheckers** [comment]
Changelog-
more comments added
Country.cs- Public string,double,int and bool changed from public to private

**Comment by smexycheckers** [comment]
Changelog-
more comments added
Country.cs- Public string,double,int and bool changed from public to private
